export default [

    //LOAD MESSAGES
    'LOAD_MESSAGES_REQUEST',
    'LOAD_MESSAGES_SUCCESS',
    'LOAD_MESSAGES_FAILURE',

    //SEND MESSAGE
    'SEND_MESSAGE_REQUEST',
    'SEND_MESSAGE_SUCCESS',
    'SEND_MESSAGE_FAILURE',

    //LOAD CONVERSATIONS
    'LOAD_CONVERSATIONS_REQUEST',
    'LOAD_CONVERSATIONS_SUCCESS',
    'LOAD_CONVERSATIONS_FAILURE',

    //CREATE CONVERSATION
    'CREATE_CONVERSATIONS_REQUEST',
    'CREATE_CONVERSATIONS_SUCCESS',
    'CREATE_CONVERSATIONS_FAILURE',

    //LOAD USERS
    'LOAD_USERS_REQUEST',
    'LOAD_USERS_SUCCESS',
    'LOAD_USERS_FAILURE',

    // Auth
    'LOGIN_REQUEST',
    'LOGIN_SUCCESS',
    'LOGIN_FAILURE',

    'FETCH_SESSION_USER_SUCCESS',

].reduce((seed, key) => ({ ...seed, [key]: key }), {});
